pub(super) const OBJECTIVE_DEFINITION_TABLE_SLOT: usize =
    crate::investment_schema::ROOT_OBJECTIVE_DEFINITION_TABLE_SLOT;
pub(super) const OBJECTIVE_STRING_TABLE_SLOT: usize =
    crate::investment_schema::GLOBALS_OBJECTIVE_STRING_TABLE_SLOT;
pub(super) const OBJECTIVE_CONDITIONS_OFFSET: usize = 0x08;
pub(super) const OBJECTIVE_SECONDARY_CONDITIONS_OFFSET: usize = 0x38;
pub(super) const OBJECTIVE_INTRINSIC_PERK_FLAGS_OFFSET: usize = 0x48;
pub(super) const OBJECTIVE_INTRINSIC_PERK_FLAG_ROW_CLASS: u32 = 0x8080_7D4B;
pub(super) const OBJECTIVE_INTRINSIC_PERK_FLAG_ROW_SIZE: usize = size_of::<u16>();
pub(super) const OBJECTIVE_ALLOW_OVERCOMPLETION_OFFSET: usize = 0x29;
pub(super) const OBJECTIVE_ALLOW_NEGATIVE_VALUE_OFFSET: usize = 0x2A;
pub(super) const OBJECTIVE_ALLOW_VALUE_CHANGE_WHEN_COMPLETED_OFFSET: usize = 0x2B;
pub(super) const OBJECTIVE_IS_COUNTING_DOWNWARD_OFFSET: usize = 0x2C;
pub(super) const ACTIVITY_DEFINITION_TABLE_SLOT: usize = 4;
pub(super) const ACTIVITY_STRING_TABLE_SLOT: usize = 3;
pub(super) const ACTIVITY_DEFINITION_ROW_CLASS: u32 = 0x8080_76FC;
pub(super) const ACTIVITY_STRING_ROW_CLASS: u32 = 0x8080_5E15;
pub(super) const ACTIVITY_INDEX_ROW_SIZE: usize = 0x10;
pub(super) const ACTIVITY_GATE_LIST_OFFSET: usize = 0x08;
pub(super) const ACTIVITY_GATE_ROW_CLASS: u32 = 0x8080_0070;
pub(super) const ACTIVITY_AVAILABILITY_TABLE_SLOT: usize = 2;
pub(super) const ACTIVITY_AVAILABILITY_LIST_OFFSET: usize = 0x30;
pub(super) const ACTIVITY_AVAILABILITY_ROW_CLASS: u32 = 0x8080_7703;
pub(super) const ACTIVITY_AVAILABILITY_ROW_SIZE: usize = 0x48;
pub(super) const ACTIVITY_AVAILABILITY_GROUP_OFFSETS: [usize; 2] = [0, 0x10];
pub(super) const ACTIVITY_AVAILABILITY_GROUP_ROW_CLASS: u32 = 0x8080_7D2F;
pub(super) const ACTIVITY_AVAILABILITY_GROUP_ROW_SIZE: usize = 0x10;
pub(super) const ACTIVITY_AVAILABILITY_GATE_HASH_OFFSET: usize = 0x40;
pub(super) const ITEM_OBJECTIVE_RESOURCE_POINTER_OFFSET: usize = 0x30;
pub(super) const ITEM_OBJECTIVE_RESOURCE_CLASS: u32 = 0x8080_77EB;
pub(super) const ITEM_OBJECTIVE_INDEX_ROW_CLASS: u32 = 0x8080_87B1;
pub(super) const COLLECTIBLE_DEFINITION_TABLE_SLOT: usize =
    crate::investment_schema::ROOT_COLLECTIBLE_DEFINITION_TABLE_SLOT;
pub(super) const METRIC_DEFINITION_TABLE_SLOT: usize = 55;
pub(super) const METRIC_STRING_TABLE_SLOT: usize = 37;
pub(super) const METRIC_DEFINITION_ROW_SIZE: usize = 0x48;
pub(super) const METRIC_STRING_ROW_SIZE: usize = 0x18;
pub(super) const METRIC_TRAIT_LIST_OFFSET: usize = 0x08;
pub(super) const METRIC_TRAIT_INDEX_ROW_CLASS: u32 = 0x8080_2C50;
pub(super) const METRIC_HASH_OFFSET: usize = 0x28;
pub(super) const METRIC_OBJECTIVE_INDEX_OFFSET: usize = 0x2C;
pub(super) const MILESTONE_DEFINITION_TABLE_SLOT: usize = 54;
pub(super) const MILESTONE_STRING_TABLE_SLOT: usize = 36;
pub(super) const MILESTONE_DEFINITION_ROW_CLASS: u32 = 0x8080_74BF;
pub(super) const MILESTONE_STRING_ROW_CLASS: u32 = 0x8080_5A00;
pub(super) const MILESTONE_DEFINITION_ROW_SIZE: usize = 0x38;
pub(super) const MILESTONE_STRING_ROW_SIZE: usize = 0x28;
pub(super) const MILESTONE_STRING_OFFSETS: [usize; 4] = [0x08, 0x10, 0x18, 0x20];
pub(super) const MILESTONE_PRIMARY_OBJECTIVE_INDEX_OFFSET: usize = 0x18;
pub(super) const MILESTONE_PHASE_COUNT_OFFSET: usize = 0x1C;
pub(super) const MILESTONE_PHASE_OBJECTIVES_OFFSET: usize = 0x20;
pub(super) const MILESTONE_PHASE_OBJECTIVE_PAIR_SIZE: usize = 0x04;
pub(super) const MILESTONE_MAX_PHASES: usize = 6;
pub(super) const TRAIT_DEFINITION_TABLE_SLOT: usize = 98;
pub(super) const TRAIT_STRING_TABLE_SLOT: usize = 62;
pub(super) const TRAIT_DEFINITION_ROW_CLASS: u32 = 0x8080_2C45;
pub(super) const TRAIT_STRING_ROW_CLASS: u32 = 0x8080_28BF;
pub(super) const TRAIT_DEFINITION_ROW_SIZE: usize = 0x08;
pub(super) const TRAIT_STRING_ROW_SIZE: usize = 0x18;
pub(super) const LOCATION_DEFINITION_TABLE_SLOT: usize = 29;
pub(super) const LOCATION_STRING_TABLE_SLOT: usize = 24;
pub(super) const LOCATION_DEFINITION_ROW_CLASS: u32 = 0x8080_7A35;
pub(super) const LOCATION_STRING_ROW_CLASS: u32 = 0x8080_5B03;
pub(super) const LOCATION_DEFINITION_ROW_SIZE: usize = 0x48;
pub(super) const LOCATION_STRING_ROW_SIZE: usize = 0x18;
pub(super) const LOCATION_RELEASE_LIST_OFFSET: usize = 0x38;
pub(super) const LOCATION_RELEASE_ROW_CLASS: u32 = 0x8080_7A3A;
pub(super) const LOCATION_RELEASE_ROW_SIZE: usize = 0x50;
pub(super) const LOCATION_RELEASE_ACTIVITY_INDEX_OFFSET: usize = 0x12;
pub(super) const LOCATION_DISPLAY_LIST_OFFSET: usize = 0x08;
pub(super) const LOCATION_DISPLAY_ROW_CLASS: u32 = 0x8080_5B05;
pub(super) const LOCATION_DISPLAY_ROW_SIZE: usize = 0x20;
pub(super) const LOCATION_RELEASE_CONDITION_TABLE_SLOT: usize = 28;
pub(super) const LOCATION_RELEASE_CONDITION_ROW_CLASS: u32 = 0x8080_7459;
pub(super) const LOCATION_RELEASE_CONDITION_ROW_SIZE: usize = 0x28;
pub(super) const LOCATION_RELEASE_LOCATION_INDEX_OFFSET: usize = 0;
pub(super) const LOCATION_RELEASE_CONDITIONS_OFFSET: usize = 0x08;
pub(super) const LOCATION_RELEASE_CONDITION_ACTIVITY_INDEX_OFFSET: usize = 0x20;
pub(super) const RECORD_DEFINITION_TABLE_SLOT: usize =
    crate::investment_schema::ROOT_RECORD_DEFINITION_TABLE_SLOT;
pub(super) const RECORD_STRING_TABLE_SLOT: usize =
    crate::investment_schema::GLOBALS_RECORD_STRING_TABLE_SLOT;
pub(super) const RECORD_OBJECTIVE_LIST_OFFSET: usize = 0x30;
pub(super) const RECORD_INTERVAL_OBJECTIVE_LIST_OFFSET: usize = 0x40;
pub(super) const RECORD_INTERVAL_OBJECTIVE_ROW_CLASS: u32 = 0x8080_2C0F;
pub(super) const RECORD_INTERVAL_OBJECTIVE_ROW_SIZE: usize = 0x0C;
pub(super) const RECORD_INTERVAL_OBJECTIVE_INDEX_OFFSET: usize = 0;
pub(super) const RECORD_CONDITION_OFFSETS: [usize; 6] = [0x68, 0x78, 0x88, 0x98, 0xA8, 0xC0];
pub(super) const PRESENTATION_NODE_DEFINITION_TABLE_SLOT: usize =
    crate::investment_schema::ROOT_PRESENTATION_NODE_DEFINITION_TABLE_SLOT;
pub(super) const PRESENTATION_NODE_STRING_TABLE_SLOT: usize =
    crate::investment_schema::GLOBALS_PRESENTATION_NODE_STRING_TABLE_SLOT;
pub(super) const PRESENTATION_NODE_CONDITION_OFFSETS: [usize; 2] = [0x30, 0x40];
pub(super) const UNLOCK_FLAG_DEFINITION_TABLE_SLOT: usize =
    crate::investment_schema::ROOT_UNLOCK_FLAG_DEFINITION_TABLE_SLOT;
pub(super) const UNLOCK_FLAG_DISPLAY_TABLE_SLOT: usize =
    crate::investment_schema::GLOBALS_UNLOCK_FLAG_DISPLAY_TABLE_SLOT;
pub(super) const UNLOCK_FLAG_DISPLAY_POINTER_OFFSET: usize = 8;
pub(super) const UNLOCK_FLAG_DISPLAY_NAME_OFFSET: usize = 0;
pub(super) const UNLOCK_FLAG_DISPLAY_DESCRIPTION_OFFSET: usize = 8;
pub(super) const UNLOCK_VALUE_DEFINITION_TABLE_SLOT: usize = 114;
pub(super) const UNLOCK_VALUE_DEFINITION_ROW_CLASS: u32 = 0x8080_7C96;
pub(super) const UNLOCK_DEFINITION_CODE_OFFSET: usize = 4;
pub(super) const UNLOCK_DEFINITION_SLOT_OFFSET: usize = 6;
pub(super) const UNLOCK_DEFINITION_UNBANKED_SLOT: u16 = u16::MAX;
pub(super) const CONDITION_FLAG_KIND: u32 = 1;
pub(super) const CONDITION_VALUE_KIND: u32 = 10;
pub(super) const CONDITION_POOL_KIND: u32 = 12;
pub(super) const PROGRESSION_DEFINITION_TABLE_SLOT: usize = 68;
pub(super) const PROGRESSION_DEFINITION_ROW_CLASS: u32 = 0x8080_7CDD;
pub(super) const PROGRESSION_DEFINITION_ROW_SIZE: usize = 88;
pub(super) const PROGRESSION_DEFINITION_HASH_OFFSET: usize = 0;
pub(super) const PROGRESSION_DEFINITION_SCOPE_OFFSET: usize = 4;
pub(super) const PROGRESSION_DEFINITION_REPEAT_LAST_STEP_OFFSET: usize = 5;
pub(super) const PROGRESSION_DEFINITION_SCOPE_SLOT_OFFSET: usize = 0x40;
pub(super) const PROGRESSION_DEFINITION_STEPS_OFFSET: usize = 24;
pub(super) const PROGRESSION_DEFINITION_REWARDS_OFFSET: usize = 72;
pub(super) const PROGRESSION_STEP_ROW_CLASS: u32 = 0x8080_7CED;
pub(super) const PROGRESSION_STEP_ROW_SIZE: usize = 8;
pub(super) const PROGRESSION_STEP_PROGRESS_TOTAL_OFFSET: usize = 0;
pub(super) const PROGRESSION_REWARD_ROW_CLASS: u32 = 0x8080_2FF7;
pub(super) const PROGRESSION_REWARD_ROW_SIZE: usize = 56;
pub(super) const PROGRESSION_REWARD_LEVEL_OFFSET: usize = 0;
pub(super) const PROGRESSION_REWARD_ITEM_INDEX_OFFSET: usize = 4;
pub(super) const PROGRESSION_REWARD_QUANTITY_OFFSET: usize = 8;
pub(super) const PROGRESSION_STRING_TABLE_SLOT: usize = 46;
pub(super) const PROGRESSION_STRING_ROW_CLASS: u32 = 0x8080_5F5D;
pub(super) const PROGRESSION_STRING_ROW_SIZE: usize = 72;
pub(super) const PROGRESSION_NAME_OFFSET: usize = 4;
pub(super) const PROGRESSION_DESCRIPTION_OFFSET: usize = 12;
pub(super) const PROGRESSION_ICON_INDEX_OFFSET: usize = 20;
pub(super) const PROGRESSION_SOURCE_OFFSET: usize = 24;
pub(super) const PROGRESSION_DISPLAY_UNITS_NAME_OFFSET: usize = 32;
pub(super) const PROGRESSION_STEP_STRINGS_OFFSET: usize = 40;
pub(super) const PROGRESSION_STEP_STRING_ROW_CLASS: u32 = 0x8080_5F5F;
pub(super) const PROGRESSION_STEP_STRING_ROW_SIZE: usize = 32;
pub(super) const PROGRESSION_STEP_NAME_OFFSET: usize = 0;
pub(super) const PROGRESSION_STEP_ICON_INDEX_OFFSET: usize = 8;
pub(super) const PROGRESSION_REWARD_STRINGS_OFFSET: usize = 56;
pub(super) const PROGRESSION_REWARD_STRING_ROW_CLASS: u32 = 0x8080_2B4B;
pub(super) const FACTION_DEFINITION_TABLE_SLOT: usize = 35;
pub(super) const FACTION_STRING_TABLE_SLOT: usize = 28;
pub(super) const FACTION_DEFINITION_ROW_CLASS: u32 = 0x8080_74CE;
pub(super) const FACTION_STRING_ROW_CLASS: u32 = 0x8080_59A2;
pub(super) const FACTION_ROW_SIZE: usize = 0x18;
pub(super) const FACTION_HASH_OFFSET: usize = 0;
pub(super) const FACTION_PROGRESSION_INDEX_OFFSET: usize = 4;
pub(super) const FACTION_NAME_OFFSET: usize = 4;
pub(super) const FACTION_DESCRIPTION_OFFSET: usize = 12;
pub(super) use crate::investment_schema::{
    COLLECTIBLE_CONDITION_OFFSETS, COLLECTIBLE_DEFINITION_ROW_CLASS,
    COLLECTIBLE_DEFINITION_ROW_SIZE, COLLECTIBLE_HASH_OFFSET,
    COLLECTIBLE_INVENTORY_ITEM_INDEX_OFFSET, COLLECTIBLE_PRESENTATION_NODE_PARENTS_OFFSET,
    CONDITION_EXPRESSION_ROW_CLASS, CONDITION_EXPRESSION_ROW_SIZE, NESTED_ARRAY_TRAILER,
    OBJECTIVE_COMPLETION_VALUE_OFFSET, OBJECTIVE_DEFINITION_ROW_CLASS,
    OBJECTIVE_DEFINITION_ROW_SIZE,
    OBJECTIVE_STRING_DESCRIPTION_REFERENCE_OFFSET as OBJECTIVE_DISPLAY_DESCRIPTION_OFFSET,
    OBJECTIVE_STRING_NAME_REFERENCE_OFFSET as OBJECTIVE_NAME_OFFSET,
    OBJECTIVE_STRING_PROGRESS_REFERENCE_OFFSET as OBJECTIVE_PROGRESS_DESCRIPTION_OFFSET,
    OBJECTIVE_STRING_ROW_SIZE, PRESENTATION_NODE_DEFINITION_ROW_CLASS,
    PRESENTATION_NODE_DEFINITION_ROW_SIZE, PRESENTATION_NODE_HASH_OFFSET,
    PRESENTATION_NODE_INDEX_ROW_CLASS, PRESENTATION_NODE_OBJECTIVE_INDEX_OFFSET,
    PRESENTATION_NODE_PARENTS_OFFSET, PRESENTATION_NODE_STRING_ROW_SIZE,
    RECORD_DEFINITION_ROW_SIZE, RECORD_HASH_OFFSET, RECORD_OBJECTIVE_INDEX_ROW_CLASS,
    RECORD_STRING_ROW_SIZE, UNLOCK_FLAG_DEFINITION_ROW_CLASS, UNLOCK_FLAG_DEFINITION_ROW_SIZE,
    UNLOCK_FLAG_DISPLAY_CONTENT_ROW_CLASS, UNLOCK_FLAG_DISPLAY_CONTENT_ROW_SIZE,
    UNLOCK_FLAG_DISPLAY_ROW_CLASS, UNLOCK_FLAG_DISPLAY_ROW_SIZE,
};
