//! Every condition kind the client registers, and the action execution policies.
use super::*;

/// Every condition kind the client registers, indexed by kind.
pub const CONDITIONS: [NodeKind; 45] = [
    NodeKind {
        kind: 0,
        class: 0x80803E03,
        struct_size: 8,
        occurrences: 909,
        name: "Unconditional Check",
        summary: "Always passes. The action still obeys its probability roll and event routing.",
        evidence: "The specific checker returns true. The common probability and event-routing checks still apply. The compiler emits it as the activation of an always-active program and carries it verbatim as an ending condition, where 41 stock actions use it to end at once.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 1,
        class: 0x80803DCD,
        struct_size: 12,
        occurrences: 527,
        name: "Timer",
        summary: "Waits for a fixed number of seconds. Used for both effect duration and cooldown.",
        evidence: "Uses timer enumeration and expiry callbacks. The specific boolean checker itself returns true.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 2,
        class: 0x80803DE7,
        struct_size: 344,
        occurrences: 396,
        name: "Kill Event",
        summary: "Fires on a kill. Can require the owning weapon and a label such as precision.",
        evidence: "Filters weapon ownership, ability labels, target properties and optional restrictions. Supplies activation target context.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 3,
        class: 0x80803DE5,
        struct_size: 288,
        occurrences: 12,
        name: "Label and Value Event Filter",
        summary: "Fires on an event that carries labels and a number, and checks both against a range.",
        evidence: "Reads both source label filters, the inclusive value range at +110, the owning-weapon flag at +118 and the optional weapon key at +11C. The event source still needs identification.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 4,
        class: 0x80802F5F,
        struct_size: 208,
        occurrences: 163,
        name: "Object and Numeric Event Filter",
        summary: "Fires on an event that references an object, then checks that object and several numbers.",
        evidence: "Reads the source label filter at +8, value threshold +A0, optional named key +9C, object filter selector +A8, source mask +C1 and whether the stateful +C8 predicate is present. That predicate keeps per target counts or fractions between evaluations. The event source and some field names remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 5,
        class: 0x80803DDC,
        struct_size: 200,
        occurrences: 20,
        name: "Distance and Numeric Event Filter",
        summary: "Fires on an event that references an object, then checks distance and a numeric threshold.",
        evidence: "Reads the source label filter at +8, threshold +98, optional named key +A0, optional maximum distance +A4 and the event masks at +B8 and +B9. Distance calculation reads protected position values, and the event source is unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 6,
        class: 0x80803DFB,
        struct_size: 12,
        occurrences: 48,
        name: "Two Event Flag Masks",
        summary: "Requires the event to carry both of two flag masks.",
        evidence: "Requires an intersection between node +8 and event byte 0. Node +9 either disables the second check or must intersect event byte 1.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 7,
        class: 0x80803DFD,
        struct_size: 32,
        occurrences: 25,
        name: "Slot and Player Filter",
        summary: "Checks the event equipment slot and the acting player.",
        evidence: "Reads the slot mask at +8 and the player filter selector at +10, which the checker applies to the event slot and acting player. The event source still needs identification.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 8,
        class: 0x80803E01,
        struct_size: 32,
        occurrences: 62,
        name: "Slot and Player Filter",
        summary: "Checks the event equipment slot and the acting player.",
        evidence: "Reads the slot mask at +8 and the player filter selector at +10, which the checker applies to the event slot and acting player. The event source still needs identification.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 9,
        class: 0x80803E00,
        struct_size: 12,
        occurrences: 16,
        name: "Event Slot Mask",
        summary: "Selects a slot bit from an event integer and requires it in the node mask.",
        evidence: "Tests node +8 against the bit selected by the event integer at +4.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 10,
        class: 0x80803DFF,
        struct_size: 24,
        occurrences: 5,
        name: "Event Key Match",
        summary: "Requires the event key to equal the key stored on this node.",
        evidence: "Requires equality between the node integer at +10 and the first event integer.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 11,
        class: 0x80803DFE,
        struct_size: 24,
        occurrences: 8,
        name: "Event Key Match",
        summary: "Requires the event key to equal the key stored on this node.",
        evidence: "Requires equality between the node integer at +10 and the first event integer.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 12,
        class: 0x80803DEA,
        struct_size: 16,
        occurrences: 31,
        name: "Key and Context Lookup",
        summary: "Matches an event value, then resolves a named key against the event context.",
        evidence: "Requires node +8 to match event +10, then resolves node key +C against the event context through 504150.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 13,
        class: 0x80803DDE,
        struct_size: 112,
        occurrences: 8,
        name: "Weapon Event Filter",
        summary: "Fires when the trigger is released on a weapon and checks the weapon labels.",
        evidence: "Reads the owning-weapon flag at +8, the slot mask at +B and the source label filter at +10, which the checker compiles into its object-label test. Handles an invalid event slot explicitly. The event is the trigger release: Dynamic Sway Reduction, Spinning Up and Lightning Rounds, which act while the trigger is held, all end on it.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 14,
        class: 0x80803DFA,
        struct_size: 112,
        occurrences: 89,
        name: "Attach Event",
        summary: "Fires when the weapon is attached to the character.",
        evidence: "Observed in the Wave Frame activation program. Target and host restrictions still apply.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 15,
        class: 0x80803DF7,
        struct_size: 112,
        occurrences: 89,
        name: "Detach Event",
        summary: "Fires when the weapon is detached from the character.",
        evidence: "Paired with the Wave Frame attach event for removal.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 16,
        class: 0x80803DF5,
        struct_size: 112,
        occurrences: 95,
        name: "Draw Event",
        summary: "Fires when the weapon is drawn.",
        evidence: "Observed in the Cluster Bomb activation program. Shares a checker with holster and related weapon events.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 17,
        class: 0x80803DDB,
        struct_size: 112,
        occurrences: 107,
        name: "Holster Event",
        summary: "Fires when the weapon is holstered.",
        evidence: "Observed in Cluster Bomb and Outlaw removal programs.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 18,
        class: 0x80803DDD,
        struct_size: 112,
        occurrences: 19,
        name: "Weapon Event Filter",
        summary: "Fires when a weapon is swapped to and checks that weapon's slot and labels.",
        evidence: "Reads the owning-weapon flag at +8, the slot mask at +B and the source label filter at +10, sharing the checker used by attach, detach, draw and holster events. The event is a weapon swap: Mecha Holster reads a Submachine Gun readied in either slot, Spring-Loaded Mounting a Sidearm swapped to, and Sprint Grip and Spinning Up end on it.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 19,
        class: 0x80803DE2,
        struct_size: 112,
        occurrences: 46,
        name: "Weapon Event with Time Restriction",
        summary: "Fires on an unnamed weapon event with an additional time restriction.",
        evidence: "Checks optional owning weapon +8, slot mask +B, time restriction +C and object labels +60. Event byte +8 selects whether node byte +9 or +A must be set.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 20,
        class: 0x80803DCE,
        struct_size: 256,
        occurrences: 293,
        name: "General Predicate",
        summary: "A general predicate over player, object, ability and value restrictions, optionally inverted.",
        evidence: "Combines state, object, ability and value restrictions, with optional final inversion. Individual fields are only partly mapped.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 21,
        class: 0x80803DFC,
        struct_size: 352,
        occurrences: 1,
        name: "Two Objects and Ability Filter",
        summary: "Checks two event objects and an ability filter.",
        evidence: "Checks valid event objects against the compiled predicates at +58 and +B8, applies ability filter +138 and optionally scans related player state when +158 is set. The reader reports that flag. The source event is unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 22,
        class: 0x80803DF9,
        struct_size: 12,
        occurrences: 6,
        name: "Event Byte Match",
        summary: "Requires an event byte to equal the byte on this node.",
        evidence: "Requires equality between node byte +8 and event byte 0.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 23,
        class: 0x80803DDA,
        struct_size: 12,
        occurrences: 26,
        name: "Event Byte with Host Restrictions",
        summary: "Requires an event byte to match, and can require the owning weapon.",
        evidence: "Matches node byte +8 with event byte +4. Node +A can require the owning weapon. Node +9 excludes host component states 1 and 2.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 24,
        class: 0x80803DE1,
        struct_size: 12,
        occurrences: 1,
        name: "Event Byte Match",
        summary: "Requires an event byte to equal the byte on this node.",
        evidence: "Requires equality between node byte +8 and event byte 0.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 25,
        class: 0x80803DDF,
        struct_size: 12,
        occurrences: 2,
        name: "Event Byte Match",
        summary: "Requires an event byte to equal the byte on this node.",
        evidence: "Requires equality between node byte +8 and event byte 0.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 26,
        class: 0x80803E30,
        struct_size: 56,
        occurrences: 142,
        name: "Accumulator",
        summary: "Counts toward a threshold. Child rows add, replace or multiply the stored value.",
        evidence: "Applies success or failure arithmetic for nested conditions, clamps the value and checks a threshold. Includes scheduled processing.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 27,
        class: 0x808029E0,
        struct_size: 152,
        occurrences: 43,
        name: "Two Objects and Event State",
        summary: "Checks two objects and the state carried by the event.",
        evidence: "Reads the owning-weapon flag +8, slot mask +9, event bytes +C and +D, the source label filter at +10, the object filter selector at +80 and mode +90, which selects restrictions on those event bytes. The source event remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 28,
        class: 0x80803DE0,
        struct_size: 12,
        occurrences: 2,
        name: "Event Mask",
        summary: "Selects a bit from an event integer and requires it in the node mask.",
        evidence: "Tests node +8 against the bit selected by the first event integer.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 29,
        class: 0x80803DEC,
        struct_size: 12,
        occurrences: 29,
        name: "Event Key Match",
        summary: "Requires the event context value to equal the key on this node.",
        evidence: "Compares the 32-bit event context value with the key stored at node +8.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 30,
        class: 0x80803DEB,
        struct_size: 12,
        occurrences: 449,
        name: "Event Key Match",
        summary: "Requires the event context value to equal the key on this node.",
        evidence: "Compares the 32-bit event context value with the key stored at node +8. The compiler emits it as the ending condition of an always-active program, the shape 216 stock actions share.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 31,
        class: 0x80803E04,
        struct_size: 24,
        occurrences: 10,
        name: "All Subgroups",
        summary: "Requires every subgroup to pass. Conditions inside one subgroup are alternatives.",
        evidence: "Requires each subgroup to pass or retain positive hold state. Conditions within each subgroup use OR semantics.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 32,
        class: 0x80803DF8,
        struct_size: 104,
        occurrences: 34,
        name: "Event Label Filter",
        summary: "Checks the labels carried by the object the event references.",
        evidence: "Applies the predicate at node +58 to the label set four bytes into the event-referenced object.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 33,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Event Byte Differs",
        summary: "Requires an event byte to differ from the byte on this node.",
        evidence: "Requires node byte +8 to differ from event byte 0. No package occurrence was found.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 34,
        class: 0x80803DE4,
        struct_size: 40,
        occurrences: 4,
        name: "Key and Two Numeric Ranges",
        summary: "Matches an optional key and requires two event numbers to fall inside stored ranges.",
        evidence: "The key at +10 may be FFFFFFFF to skip key matching. The two event floats must lie within node ranges +18..+1C and +20..+24.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 35,
        class: 0x80803DCC,
        struct_size: 264,
        occurrences: 244,
        name: "Predicate with Nested Condition",
        summary: "Runs the general predicate and then a second nested condition.",
        evidence: "Runs the kind 20 general predicate and then the nested condition at +100. Maintains separate state routing.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 36,
        class: 0x80803DF6,
        struct_size: 12,
        occurrences: 8,
        name: "Event Byte Match",
        summary: "Requires an event byte to equal the byte on this node.",
        evidence: "Requires equality between node byte +8 and event byte 0.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 37,
        class: 0x80802D02,
        struct_size: 12,
        occurrences: 1,
        name: "Nonempty Event Key Match",
        summary: "Requires a nonempty key on this node to equal the event key.",
        evidence: "Requires node +8 to be nonempty and equal the first event integer. Empty uses the FNV offset-basis value 811C9DC5.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 38,
        class: 0x80802D01,
        struct_size: 16,
        occurrences: 2,
        name: "Named Target Beyond Distance",
        summary: "Requires a named target to be farther away than the stored distance.",
        evidence: "Requires a matching nonempty key, resolves its target and compares squared distance with the square of node float +C.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 39,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Event Integer Match",
        summary: "Requires an event integer to equal the integer on this node.",
        evidence: "Requires equality between node integer +8 and event integer 0. No package occurrence was found.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 40,
        class: 0x80802D00,
        struct_size: 144,
        occurrences: 1,
        name: "Named Event with Four Object Filters",
        summary: "Matches an optional named event and applies four object filters.",
        evidence: "Reads the optional key at +8. The checker matches it, then applies the filters at +10, +30, +50 and +70 to three event weak handles and the controller player.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 41,
        class: 0x808029E1,
        struct_size: 40,
        occurrences: 12,
        name: "Object and Slot Filter",
        summary: "Checks an event slot mask and then an object filter against the event object and weapon.",
        evidence: "Reads the four-slot event mask at +8 and the object filter selector at +18. The checker applies that filter to the event object and owning weapon.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 42,
        class: 0x808029E6,
        struct_size: 12,
        occurrences: 14,
        name: "Event Byte at +8 Match",
        summary: "Requires the event byte at offset 8 to equal the byte on this node.",
        evidence: "Requires node byte +8 to equal event byte +8.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 43,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Event Object Filter",
        summary: "Applies an object filter to the event object.",
        evidence: "Rejects an invalid event object, then evaluates node filter +8 against it and the controller player. No package occurrence was found.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 44,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Event Object Filter",
        summary: "Applies an object filter to the event object.",
        evidence: "Rejects an invalid event object, then evaluates node filter +8 against it and the controller player. No package occurrence was found.",
        support: Support::Unobserved,
    },
];
