//! Every effect kind the client registers, indexed by kind.
use super::*;

/// Every effect kind the client registers, indexed by kind.
pub const EFFECTS: [NodeKind; 55] = [
    NodeKind {
        kind: 0,
        class: 0x80803E4C,
        struct_size: 2,
        occurrences: 1,
        name: "Target Component Gate",
        summary: "Opens a gate on the target component while the action is active.",
        evidence: "Resolves an activation target, retains its weak handle and sets gate 1 through CA4910. Cleanup clears that gate. CA4910 combines two gate inputs into host byte +A48. The node stores no fields beyond its header. The downstream feature remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 1,
        class: 0x80803E45,
        struct_size: 64,
        occurrences: 1011,
        name: "Create Entity",
        summary: "Attaches a referenced entity, with configurable cleanup when the action ends.",
        evidence: "1089400 creates the graph on EC0AA0's selected object and can initialize a named parameter from action state. 108B550 handles removal: a nonempty cleanup key suppresses the automatic retirement branch, and an optional named four-lane parameter is written to the entity. The key alone does not select the entity's gameplay behavior.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 2,
        class: 0x80803E44,
        struct_size: 88,
        occurrences: 95,
        name: "Create Entity with Dynamic Value",
        summary: "Creates a referenced entity and drives one of its numbers from a value program.",
        evidence: "Creates the referenced entity, retains its handle and applies the program at +20 to its numeric component state. Slot 1 recomputes the value using input selector +50 and normalization flag +51.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 3,
        class: 0x80803E43,
        struct_size: 24,
        occurrences: 42,
        name: "Spawn Entity at Selected Transform",
        summary: "Spawns a referenced entity once at a selected position. It then owns its own lifetime.",
        evidence: "Creates the entity resource at +10, chooses its position and attachment using bytes +2 through +4 and activation context, then submits it through 56D990. No retained cleanup callback is registered.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 4,
        class: 0x80803E46,
        struct_size: 24,
        occurrences: 8,
        name: "Apply Referenced Resource to Target",
        summary: "Applies a referenced resource to a selected target.",
        evidence: "Target selector +2 resolves the target. Resource +10 is consumed through either CDA100 and DD9C60 or the entity creation path, depending on its resource type.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 5,
        class: 0x80803E42,
        struct_size: 32,
        occurrences: 8,
        name: "Generate Orbs of Light",
        summary: "Generates Orbs of Light for player recipients, with a count, value and location. Publishes the generation event. Use a spawn action for health pickups and other objects.",
        evidence: "Callback 1089AF0 uses EC0FC0 to select the owner position (0) or activation event position (1), then passes count +4, orb value +8 and a resource reference at +18 to FBC3E0. Masterwork Weapon 453 and Trinity Ghoul Catalyst 2010 use entity 80EFAE02. Striking Light 1803 and Light of the Fire 1960 use its default entity. The downstream helper accepts an entity argument and selects player recipients, but that does not establish that this perk action honors arbitrary pickup overrides. Stock sources establish orb generation. The resource reference's effect on pickup type remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 6,
        class: 0x80803E41,
        struct_size: 4,
        occurrences: 9,
        name: "Set Host Mode",
        summary: "Sets a mode byte on the host and restores it on removal unless persistence is requested.",
        evidence: "Writes byte +2 through the selected ability interface or DAB210. Cleanup resets the mode unless byte +3 requests persistence. Mode 0 is Kinetic, 1 Solar, 2 Arc and 3 Void, established by the stock plugs that set each value: Solar, Arc and Void Damage Mod name their element, The Fundamentals sets all three and is described in game as changing the weapon's damage type, and Play with Your Prey sets 1 and 3 while describing a Solar and a Void rocket.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 7,
        class: 0x80803E1D,
        struct_size: 12,
        occurrences: 81,
        name: "Ability Property",
        summary: "Changes a named property inside an ability bank.",
        evidence: "Targets a named property in an ability bank. Previously traced with sandbox perk 166.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 8,
        class: 0x80803E4D,
        struct_size: 80,
        occurrences: 179,
        name: "Component Value Adjustment",
        summary: "Scales a selected component value by a value program, with an optional limit.",
        evidence: "Reads the selector bytes at +2 through +4, the scale at +8, the limit at +C, the input selector at +48 and the value program at +18. The callback multiplies the scale by the evaluated program and optionally limits movement toward the limit. The exact component slot names remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 9,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 10,
        class: 0x808029ED,
        struct_size: 80,
        occurrences: 203,
        name: "Named Property",
        summary: "Changes a named property on the weapon or an ability, with an explicit restore policy.",
        evidence: "Evaluates a value, chooses native or ability targets and applies arithmetic to a named key. Has explicit cleanup policies. The compiler emits the constant value program that 200 of the 203 stock nodes use.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 11,
        class: 0x80803E35,
        struct_size: 48,
        occurrences: 5,
        name: "Add Host Numeric Modifiers",
        summary: "Adds shared and per slot numbers into a host component, and subtracts them on removal.",
        evidence: "Reads the two shared floats at +4 and +8 and the three slot-specific triples from +C through +2C, which the callback adds into a host component. Cleanup subtracts the same values. Downstream property names remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 12,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 13,
        class: 0x80803E47,
        struct_size: 64,
        occurrences: 12,
        name: "Weighted Spawn Operation",
        summary: "Picks one of three weighted categories and spawns from the sampled range.",
        evidence: "Chooses one of three categories using weights +20, +2C and +38, then samples its configured range. Flags +3 and +4 control owner and related-player paths. The optional resource at +10 is attached to the spawned result. The categories are the ammo types, established by the stock perks that weight exactly one: Snapload Finisher (Primary ammo) the first, Special Finisher, Extra Reserves and Swift Charge (Special ammo) the second, Heavy Finisher, Giving Hand and the Voltaic Ammo Collectors (Heavy ammo) the third.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 14,
        class: 0x80803E3F,
        struct_size: 136,
        occurrences: 37,
        name: "Fixed Ammunition Adjustment",
        summary: "Adds a fixed number of rounds to the magazine or reserves of a weapon slot or ammo type.",
        evidence: "Reads the source label filter at +8, the storage path, overflow, unit-scaling and action-value bytes at +68 through +6B and the seven signed contributions at +6C through +84 for the owning slot, three weapon slots and three ammunition categories. Stock use reads storage path 1 as the magazine (Triple Tap and Fourth Time's the Charm return 1 and 2 rounds through it) and path 0 as reserves (the ammo pickup perks add to the ammo types through it). The compiler emits a label-free node with one amount, the shape 30 of the 37 stock nodes take.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 15,
        class: 0x80803E3E,
        struct_size: 136,
        occurrences: 35,
        name: "Proportional Ammunition Adjustment",
        summary: "Adds a share of a capacity, such as half a magazine, to the magazine or reserves.",
        evidence: "Reads the source label filter at +8, the destination, overflow, capacity-source and action-value bytes at +68 through +6B and the seven float contributions at +6C through +84. The callback sums them, multiplies by the selected capacity and rounds before applying. Its entry passes through protected code. Stock kill perks pair destination 1 with capacity source 1 (a kill from this weapon refills half or all of the magazine) and the ammo pickup perks pair 0 with 0, so the compiler reads 1 as the magazine and 0 as reserves. It emits a label-free node with one amount, the shape 40 of the 48 stock nodes take.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 16,
        class: 0x808029EC,
        struct_size: 392,
        occurrences: 37,
        name: "Transfer Reserve Ammunition",
        summary: "Moves ammunition from reserves into the magazine.",
        evidence: "Reads the source label filter at +8, the overflow, capacity-basis, event, input-selector and normalization bytes at +68 through +6C and the five value programs at +78, +B0, +E8, +120 and +158. The callback sums the applicable programs, rounds to an ammunition unit, caps by reserve availability and applies the amount to the magazine, then sends the remaining reserve to CC7BB0. Both its entry and that setter pass through protected code.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 17,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 18,
        class: 0x80803E23,
        struct_size: 16,
        occurrences: 2,
        name: "Radar Overrides",
        summary: "Overrides radar settings and restores their previous values when the effect ends.",
        evidence: "108D4B0 calls D9A310 for radar component slots 1, 2 and 3. D98420 and D8F2D0 propagate these settings to the player HUD. Negative values leave a setting unchanged. Slot 3 is detection range, independently identified by Long March and Radar Booster. The first two settings remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 19,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 20,
        class: 0x80803E24,
        struct_size: 3,
        occurrences: 2,
        name: "Enhanced Radar",
        summary: "Adds or removes a contribution to radar detail, reversing it when the effect ends.",
        evidence: "D8EBF0 adjusts radar component counter +90 and clamps it at zero. D98420 calls D8F2D0, which adds one to the HUD radar detail mode while the counter is positive and clamps the mode to 0 through 2. Upgraded Sensor Pack activates this effect while crouching. It is separate from radar visibility while aiming.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 21,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 22,
        class: 0x80803E0F,
        struct_size: 5,
        occurrences: 1,
        name: "Set Ability Enum",
        summary: "Writes an enum byte on the selected ability and restores it on removal.",
        evidence: "Selects the owning slot and explicit slot mask, writes byte +4 through interface slot +1F8 and retains previous values for cleanup. Enum names remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 23,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Adjust Ability Enum",
        summary: "Adds to the enum byte on the selected ability, clamped to its range.",
        evidence: "Shares kind 22 handling but adds signed byte +4 to the current value and clamps to 0 through 3. No package occurrence was found.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 24,
        class: 0x80803E14,
        struct_size: 2,
        occurrences: 1,
        name: "Magazine Component Flag",
        summary: "Sets a flag byte on the magazine component and clears it on removal.",
        evidence: "Sets the selected magazine component byte +238. Cleanup clears it. The node stores no fields beyond its header. The consumer of this flag remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 25,
        class: 0x80803E13,
        struct_size: 8,
        occurrences: 5,
        name: "Pattern Component Key Override",
        summary: "Overrides a key on the pattern component and clears it on removal.",
        evidence: "Writes the key at +4 into pattern component +64 through CA4A60. Slot 1 reapplies it and cleanup clears it. The key consumer remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 26,
        class: 0x80803E12,
        struct_size: 24,
        occurrences: 30,
        name: "Pattern Override",
        summary: "Replaces the projectile pattern used by the owning weapon while the action is active.",
        evidence: "Writes a pattern tag into the owning weapon component. Cleanup clears the override. Host compatibility remains separate.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 27,
        class: 0x808029EB,
        struct_size: 2,
        occurrences: 7,
        name: "Host Activation Counter",
        summary: "Activates a counter on the owning ability or host, and reverses it on removal.",
        evidence: "Resolves an owning ability or fallback host component and activates its counter. The fallback increments host byte +236. Cleanup reverses the operation. The gameplay feature remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 28,
        class: 0x80803E0C,
        struct_size: 24,
        occurrences: 8,
        name: "Two Ability State Overrides",
        summary: "Replaces two ability state bytes and restores them on removal.",
        evidence: "Selects the owning ability, retains two bytes, then writes node bytes +2 and +3 through two interface setters. Slot 1 reapplies them and cleanup restores the retained values.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 29,
        class: 0x80803E0B,
        struct_size: 16,
        occurrences: 10,
        name: "Three Weapon Float Overrides",
        summary: "Replaces three weapon floats and restores them on removal.",
        evidence: "Retains weapon values +6A0, +6A4 and +6A8, then replaces them from node +4, +8 and +C. Slot 1 reapplies the override and cleanup restores the values. Their downstream consumers remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 30,
        class: 0x80803E0D,
        struct_size: 3,
        occurrences: 3,
        name: "Weapon Reference Count",
        summary: "Adds a reference count on the weapon, and removes it on removal.",
        evidence: "Byte +2 increments or decrements weapon byte +AC0 through CC9350. Crossing zero updates other weapon state. Cleanup applies the inverse operation, with retained state used to gate removal.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 31,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 32,
        class: 0x80803E3B,
        struct_size: 40,
        occurrences: 30,
        name: "Extend Timers",
        summary: "Extends the timers that are already running, up to a cap, when its conditions match.",
        evidence: "The controller evaluates its nested conditions and extends eligible active timers by an amount up to a cap. The compiler nests the program's own kill trigger, as Outlaw does.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 33,
        class: 0x80803E3C,
        struct_size: 184,
        occurrences: 43,
        name: "Incoming Damage Multiplier",
        summary: "Multiplies matching incoming damage while the effect is active, optionally within a maximum source distance.",
        evidence: "1088E80 evaluates damage filter +80, then compares squared source-to-recipient distance with +C squared when +C is nonnegative. Selector +8 equal to FF uses multiplier +4, otherwise it reads a native stat. CD3020 registers the descriptor with the health component and CDDDD0 removes it. CD3570 consumes its result as an incoming-damage multiplier. Native stat identities remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 34,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 35,
        class: 0x80803E1C,
        struct_size: 12,
        occurrences: 5,
        name: "Override Host Key",
        summary: "Replaces a named key on a host property and restores it on removal.",
        evidence: "Target selector +2 and interface selector +3 choose a host property. Key +4 replaces its stored key through F67620 selectors 3 or 14. Cleanup restores the retained key. Flag +8 can apply the same operation to the controller player.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 36,
        class: 0x80803E19,
        struct_size: 16,
        occurrences: 1,
        name: "Register Host Record",
        summary: "Registers a typed record on the host and removes it on removal.",
        evidence: "Resolves host component +3E0 and registers the optional typed record at +8 through D6F7A0 using the action identity. Cleanup removes the record.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 37,
        class: 0x80803E1A,
        struct_size: 208,
        occurrences: 14,
        name: "Add Event Labels After Ability Filter",
        summary: "Adds labels to an event after an ability filter passes.",
        evidence: "Reads the source label array at +98, whose expansion reproduces the compiled set at +A8. The callback evaluates ability filter +78, then unions that set into the event through B7C590 in event callback slot 1.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 38,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 39,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 40,
        class: 0x80802F16,
        struct_size: 336,
        occurrences: 175,
        name: "Event Numeric Modifier",
        summary: "Adjusts damage after object, ability and label filters pass.",
        evidence: "B839B0 supplies damage-event fields through EC0500 and ECFDD0 to callback 108ED90. Rows at +120 assign and rows at +130 multiply a field selected by their first byte. Field 0 scales base damage and field 1 changes the precision bonus. Other damage lanes remain unnamed. The expression at +140 multiplies a separate overall damage scalar by one plus its value. Object filters at +28, source labels at +C0 and ability filters still apply. Nonliteral stat identities remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 41,
        class: 0x80803E39,
        struct_size: 8,
        occurrences: 7,
        name: "Named Host Reference Counts",
        summary: "Increments named counters on the host and decrements them on removal.",
        evidence: "Selects owner and slot targets, increments key +4 in each host named counter through DA6BC0 and retains the affected handles. Cleanup decrements the same key and removes entries whose count reaches zero.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 42,
        class: 0x80803E2F,
        struct_size: 8,
        occurrences: 147,
        name: "Accumulator Update",
        summary: "Writes the action accumulator value.",
        evidence: "Calls the common action accumulator setter. The stored mode selects the supplied value.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 43,
        class: 0x80803E1E,
        struct_size: 8,
        occurrences: 8,
        name: "Publish Named Player Event",
        summary: "Publishes a named player event.",
        evidence: "If key +4 is nonempty and the owner is valid and authoritative, publishes that key through the event-message machinery. Receiver semantics remain unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 44,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 45,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 46,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 47,
        class: 0x80803E2E,
        struct_size: 8,
        occurrences: 104,
        name: "Transmat Context, Consumer Unresolved",
        summary: "Carries a transmat key. No consumer for that key has been established.",
        evidence: "All registered callbacks are defaults. Its 104 action occurrences serve 112 perk indices. Every index has a cached Transmat Effect item reference, providing presentation context without proving the consumer of key +4. No substantive consumer was established in the inspected controller region.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 48,
        class: 0x80802D0A,
        struct_size: 24,
        occurrences: 51,
        name: "Referenced Runtime Operation",
        summary: "Runs a referenced runtime operation against three resolved targets.",
        evidence: "Stores three target selectors at +2 through +4 and the referenced runtime resource tag at +10. The native declaration marks +8 as a relative string pointer, and stock records resolve it to a resource path. It is not an operation value. The downstream operation still needs semantic identification.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 49,
        class: 0x80802D0D,
        struct_size: 8,
        occurrences: 2,
        name: "Bind Named Target",
        summary: "Binds a named target on the host. The host keeps at most four bindings.",
        evidence: "Resolves target selector +2 and adds or replaces key +4 in the host named-target list through EBCB90. The list holds up to four key, weak-target and time records.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 50,
        class: 0x00000000,
        struct_size: 0,
        occurrences: 0,
        name: "Unobserved Kind",
        summary: "Registered by the client. No surveyed action uses it, and its behavior is unclassified.",
        evidence: "Individual gameplay semantics remain unclassified.",
        support: Support::Unobserved,
    },
    NodeKind {
        kind: 51,
        class: 0x80802D03,
        struct_size: 3,
        occurrences: 1,
        name: "Append Weapon Enum",
        summary: "Appends an enum byte to a weapon list, capped at four entries.",
        evidence: "Appends byte +2 to a selected weapon list at +BC4, capped at four entries. Cleanup removes a matching entry. The enum consumer remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 52,
        class: 0x808029F1,
        struct_size: 12,
        occurrences: 2,
        name: "Add Named Player Float",
        summary: "Adds a float under a named key in a player table, and subtracts it on removal.",
        evidence: "Adds float +8 under key +4 in a player table through BF6310 and BF2C80. Cleanup adds the negated float. The table holds at most four keys, and the consuming player system remains unresolved.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 53,
        class: 0x808029F2,
        struct_size: 96,
        occurrences: 2,
        name: "Adjust Named Component Values",
        summary: "Adds, replaces or multiplies matching named component values.",
        evidence: "Reads the component name array at +8, the upper cap at +18, the value program at +28 and the operation byte at +5A. The callback adds, replaces or multiplies each matching component value according to that byte.",
        support: Support::Authorable,
    },
    NodeKind {
        kind: 54,
        class: 0x8080281C,
        struct_size: 168,
        occurrences: 9,
        name: "Add Event Labels After Object Filter",
        summary: "Adds labels to an event after an object filter passes.",
        evidence: "Reads the source label array at +68, whose expansion reproduces the compiled set at +78, and the event flag at +A0. The callback checks the event object predicate at +58 and that flag, then unions the set into the event through B7C590.",
        support: Support::Authorable,
    },
];
