//! Every value the installed stock perks set for each native selector byte, with how many
//! of their actions set it and which named perks those are.
//!
//! A selector's meaning is not recovered from any string. What the game itself does with the
//! byte is recoverable, and it is the evidence a reader needs: when every perk that sets a
//! value is a grenade-payload perk, the value is about the fired projectile. Showing the
//! perks lets a reader judge that for themselves instead of trusting a label this project
//! invented. A count is evidence of use; the perk names are evidence of meaning.
//!
//! Generated by the scratch tool `taginfo/src/bin/selectors.rs` over the 1,800 stock perk
//! actions from the clean Shadowkeep packages. Regenerate it when the corpus changes.

/// One selector byte: its native class, its byte offset, and the values stock perks set for
/// it with how many actions set each and up to three of the named perks that do.
pub type Selector = (u32, usize, &'static [(u8, u32, &'static str)]);

pub const OBSERVED: &[Selector] = &[
    (
        0x808029E0,
        0x4,
        &[(255, 13, "Box Breathing, Slideshot, Under Pressure")],
    ),
    (
        0x808029E0,
        0x9,
        &[
            (0, 12, "Box Breathing, Slideshot, Under Pressure"),
            (2, 1, "Looks Can Kill"),
        ],
    ),
    (
        0x808029E0,
        0x90,
        &[
            (0, 9, "Box Breathing, Slideshot, Under Pressure"),
            (1, 3, "Mulligan, Reversal of Fortune, Looks Can Kill"),
            (3, 1, "Taken Predator"),
        ],
    ),
    (
        0x808029E0,
        0xC,
        &[(0, 13, "Box Breathing, Slideshot, Under Pressure")],
    ),
    (
        0x808029E0,
        0xD,
        &[(0, 13, "Box Breathing, Slideshot, Under Pressure")],
    ),
    (
        0x808029E1,
        0x4,
        &[(
            255,
            3,
            "Blessing of the Sky, Unstoppable Burst, Lumina Catalyst",
        )],
    ),
    (
        0x808029E1,
        0x8,
        &[
            (1, 2, "Blessing of the Sky, Lumina Catalyst"),
            (0, 1, "Unstoppable Burst"),
        ],
    ),
    (
        0x808029E6,
        0x4,
        &[(
            255,
            4,
            "Bulwark Finisher, Spheromatik Trigger, Empowered Finish",
        )],
    ),
    (
        0x808029E6,
        0x8,
        &[
            (0, 2, "Spheromatik Trigger, Reactive Pulse"),
            (1, 2, "Bulwark Finisher, Empowered Finish"),
            (2, 1, "Reactive Pulse"),
        ],
    ),
    (
        0x808029EC,
        0x69,
        &[
            (1, 26, "Wraithmetal Mail, Auto-Loading Link, Mecha Holster"),
            (
                0,
                7,
                "Auto-Loading Holster, Superconductor, Serve the Colony",
            ),
        ],
    ),
    (
        0x808029EC,
        0x6B,
        &[
            (
                255,
                30,
                "Wraithmetal Mail, Auto-Loading Link, Mecha Holster",
            ),
            (0, 3, "Ambitious Assassin, Overflow, Clown Cartridge"),
        ],
    ),
    (
        0x808029ED,
        0x2,
        &[
            (0, 84, "Hawkeye Hack, Relentless Tracker, Horns of Doom"),
            (1, 33, "Sunfire Furnace, Accomplice, MIDA Multi-Tool"),
            (2, 16, "Cluster Bomb, Timed Payload, Explosive Payload"),
        ],
    ),
    (
        0x808029ED,
        0x3,
        &[(1, 129, "Hawkeye Hack, Relentless Tracker, Horns of Doom")],
    ),
    (
        0x808029ED,
        0x48,
        &[
            (0, 128, "Hawkeye Hack, Relentless Tracker, Horns of Doom"),
            (2, 3, "Sharp Edges, Roving Assassin, Blessing of Rasputin"),
        ],
    ),
    (
        0x808029ED,
        0x49,
        &[
            (0, 99, "Hawkeye Hack, Relentless Tracker, Horns of Doom"),
            (
                1,
                32,
                "Sharp Edges, Roving Assassin, Unforeseen Repercussions",
            ),
            (3, 1, "Revolution"),
        ],
    ),
    (
        0x808029ED,
        0x4A,
        &[
            (1, 98, "Hawkeye Hack, Relentless Tracker, Horns of Doom"),
            (
                2,
                28,
                "Auto Rifle Ammo Finder, Bow Ammo Finder, Fusion Rifle Ammo Finder",
            ),
            (
                0,
                8,
                "Sharp Edges, Roving Assassin, Unforeseen Repercussions",
            ),
        ],
    ),
    (
        0x808029ED,
        0x4B,
        &[(0, 129, "Hawkeye Hack, Relentless Tracker, Horns of Doom")],
    ),
    (0x80802D01, 0x4, &[(255, 1, "Vengeance")]),
    (0x80802D02, 0x4, &[(255, 1, "Vengeance")]),
    (0x80802D03, 0x2, &[(0, 1, "Radar Tuner")]),
    (
        0x80802D0A,
        0x2,
        &[
            (0, 17, "Conduction Tines, Sharp Edges, Overflowing Light"),
            (
                1,
                14,
                "Crystalline Transistor, Cross Counter, Dreambane Mod",
            ),
            (3, 3, "Dragonfly, Parasitism, Meganeura"),
        ],
    ),
    (
        0x80802D0A,
        0x3,
        &[
            (0, 22, "Conduction Tines, Dragonfly, Sharp Edges"),
            (1, 11, "Cross Counter, High-Energy Fire, Striking Light"),
            (3, 1, "Crystalline Transistor"),
        ],
    ),
    (
        0x80802D0A,
        0x4,
        &[
            (0, 22, "Conduction Tines, Dragonfly, Sharp Edges"),
            (
                1,
                12,
                "Crystalline Transistor, Cross Counter, High-Energy Fire",
            ),
        ],
    ),
    (0x80802D0D, 0x2, &[(3, 1, "Vengeance")]),
    (0x80802D0D, 0x3, &[(0, 1, "Vengeance")]),
    (
        0x80802F5F,
        0x4,
        &[(
            255,
            46,
            "Synapse Junctions, Probability Matrix, Relentless Tracker",
        )],
    ),
    (
        0x80802F5F,
        0xA8,
        &[
            (
                0,
                46,
                "Synapse Junctions, Probability Matrix, Relentless Tracker",
            ),
            (1, 1, "Vorpal Weapon"),
        ],
    ),
    (
        0x80802F5F,
        0xC0,
        &[
            (
                0,
                46,
                "Synapse Junctions, Probability Matrix, Relentless Tracker",
            ),
            (1, 1, "Looks Can Kill"),
        ],
    ),
    (
        0x80802F5F,
        0xC1,
        &[
            (
                0,
                43,
                "Synapse Junctions, Probability Matrix, Relentless Tracker",
            ),
            (4, 4, "Genesis, Ionic Return, Shield Disorient"),
            (2, 1, "Archer's Gambit"),
        ],
    ),
    (
        0x80803DCC,
        0x4,
        &[(
            255,
            75,
            "Wish-Dragon Teeth, Dreaded Visage, Linear Actuators",
        )],
    ),
    (
        0x80803DCD,
        0x4,
        &[(
            255,
            153,
            "Wish-Dragon Teeth, Hawkeye Hack, Relentless Tracker",
        )],
    ),
    (
        0x80803DCE,
        0x4,
        &[(
            255,
            114,
            "Spring-Loaded Mounting, Upgraded Sensor Pack, Hawkeye Hack",
        )],
    ),
    (
        0x80803DDA,
        0x4,
        &[(255, 14, "Full Choke, Hip-Fire Grip, Rangefinder")],
    ),
    (
        0x80803DDA,
        0x8,
        &[
            (1, 14, "Full Choke, Hip-Fire Grip, Rangefinder"),
            (0, 13, "Full Choke, Hip-Fire Grip, Rangefinder"),
        ],
    ),
    (
        0x80803DDA,
        0x9,
        &[(0, 14, "Full Choke, Hip-Fire Grip, Rangefinder")],
    ),
    (
        0x80803DDA,
        0xB,
        &[(0, 14, "Full Choke, Hip-Fire Grip, Rangefinder")],
    ),
    (
        0x80803DDB,
        0x4,
        &[(
            255,
            71,
            "Spring-Loaded Mounting, Upgraded Sensor Pack, Full Choke",
        )],
    ),
    (
        0x80803DDB,
        0xB,
        &[(
            0,
            71,
            "Spring-Loaded Mounting, Upgraded Sensor Pack, Full Choke",
        )],
    ),
    (
        0x80803DDC,
        0x4,
        &[(255, 4, "Fury Conductors, Taken Barrier, Fallen Barrier")],
    ),
    (
        0x80803DDC,
        0xB8,
        &[(0, 4, "Fury Conductors, Taken Barrier, Fallen Barrier")],
    ),
    (
        0x80803DDC,
        0xB9,
        &[(0, 4, "Fury Conductors, Taken Barrier, Fallen Barrier")],
    ),
    (
        0x80803DDD,
        0x4,
        &[(255, 5, "Mecha Holster, Tesseract, Sprint Grip")],
    ),
    (
        0x80803DDD,
        0xB,
        &[(0, 5, "Mecha Holster, Tesseract, Sprint Grip")],
    ),
    (0x80803DDF, 0x4, &[(255, 1, "Striking Light")]),
    (
        0x80803DDF,
        0x8,
        &[(0, 1, "Striking Light"), (1, 1, "Striking Light")],
    ),
    (
        0x80803DE2,
        0x4,
        &[(255, 20, "Ambitious Assassin, Under Pressure, Kill Clip")],
    ),
    (
        0x80803DE2,
        0xB,
        &[
            (0, 19, "Ambitious Assassin, Under Pressure, Kill Clip"),
            (2, 1, "Ionic Return"),
        ],
    ),
    (
        0x80803DE2,
        0xC,
        &[(0, 20, "Ambitious Assassin, Under Pressure, Kill Clip")],
    ),
    (
        0x80803DE4,
        0x4,
        &[(255, 2, "Explosive Light, Taking Charge")],
    ),
    (
        0x80803DE7,
        0x140,
        &[
            (0, 74, "Hawkeye Hack, Horns of Doom, Transfusion Matrix"),
            (1, 3, "Taken Armaments, Fallen Armaments, Hive Armaments"),
            (2, 2, "Roving Assassin, Ascending Amplitude"),
        ],
    ),
    (
        0x80803DE7,
        0x4,
        &[(255, 79, "Hawkeye Hack, Horns of Doom, Transfusion Matrix")],
    ),
    (
        0x80803DEA,
        0x4,
        &[(255, 9, "Recuperation, Better Already, Innervation")],
    ),
    (
        0x80803DEB,
        0x4,
        &[(255, 7, "Kill Clip, Vanishing Shadow, Cross Counter")],
    ),
    (
        0x80803DEC,
        0x4,
        &[(255, 14, "Vanishing Shadow, Touch of Venom, Noble Rounds")],
    ),
    (
        0x80803DF5,
        0x4,
        &[(
            255,
            58,
            "Spring-Loaded Mounting, Illegally Modded Holster, Auto-Loading Link",
        )],
    ),
    (
        0x80803DF5,
        0xB,
        &[(
            0,
            58,
            "Spring-Loaded Mounting, Illegally Modded Holster, Auto-Loading Link",
        )],
    ),
    (
        0x80803DF7,
        0x4,
        &[(255, 59, "Smoothbore, Drop Mag, Blinding Grenades")],
    ),
    (
        0x80803DF7,
        0xB,
        &[(0, 59, "Smoothbore, Drop Mag, Blinding Grenades")],
    ),
    (
        0x80803DF8,
        0x4,
        &[(255, 4, "Ionic Return, Last Stand, Dearly Departed")],
    ),
    (
        0x80803DF9,
        0x4,
        &[(255, 3, "Field Prep, Firmly Planted, Sneak Bow")],
    ),
    (
        0x80803DF9,
        0x8,
        &[
            (0, 3, "Field Prep, Firmly Planted, Sneak Bow"),
            (1, 3, "Field Prep, Firmly Planted, Sneak Bow"),
        ],
    ),
    (
        0x80803DFA,
        0x4,
        &[(255, 60, "Smoothbore, Drop Mag, Blinding Grenades")],
    ),
    (
        0x80803DFA,
        0xB,
        &[(0, 60, "Smoothbore, Drop Mag, Blinding Grenades")],
    ),
    (
        0x80803DFB,
        0x4,
        &[(
            255,
            19,
            "Payday, Auto Rifle Scavenger, Fusion Rifle Scavenger",
        )],
    ),
    (
        0x80803DFB,
        0x8,
        &[
            (
                3,
                11,
                "Auto Rifle Scavenger, Fusion Rifle Scavenger, Grenade Launcher Scavenger",
            ),
            (
                4,
                5,
                "Rocket Launcher Scavenger, Sword Scavenger, Machine Gun Scavenger",
            ),
            (7, 2, "Cold Fusion, Lead from Gold"),
            (1, 1, "Payday"),
        ],
    ),
    (
        0x80803DFB,
        0x9,
        &[
            (
                1,
                6,
                "Auto Rifle Scavenger, Pulse Rifle Scavenger, Scout Rifle Scavenger",
            ),
            (
                2,
                6,
                "Fusion Rifle Scavenger, Grenade Launcher Scavenger, Shotgun Scavenger",
            ),
            (
                4,
                6,
                "Rocket Launcher Scavenger, Sword Scavenger, Machine Gun Scavenger",
            ),
            (0, 1, "Payday"),
        ],
    ),
    (
        0x80803DFD,
        0x4,
        &[(255, 4, "Solar Rampart, Planetary Torrent, Burning Souls")],
    ),
    (
        0x80803DFD,
        0x8,
        &[
            (128, 3, "Solar Rampart, Planetary Torrent, Burning Souls"),
            (3, 1, "Beacons of Empowerment"),
            (4, 1, "Beacons of Empowerment"),
        ],
    ),
    (
        0x80803DFE,
        0x4,
        &[(255, 6, "Sunfire Furnace, Helium Spirals, Fusion Harness")],
    ),
    (
        0x80803DFF,
        0x4,
        &[(255, 4, "Fusion Harness, New Tricks, Scissor Fingers")],
    ),
    (
        0x80803E00,
        0x4,
        &[(255, 4, "Aeon Energy, Resolute, Sharp Edges")],
    ),
    (
        0x80803E01,
        0x4,
        &[(255, 21, "Wraithmetal Mail, Survival Well, Jump Jets")],
    ),
    (
        0x80803E01,
        0x8,
        &[
            (
                2,
                9,
                "Seriously, Watch Out, Empowering Largesse, Radiant Largesse",
            ),
            (128, 9, "Wraithmetal Mail, Survival Well, Misdirection"),
            (1, 2, "Aeon Energy, Chaotic Exchanger"),
            (8, 1, "Jump Jets"),
        ],
    ),
    (0x80803E03, 0x4, &[(255, 377, "Anarchy, Hush, Telesto")]),
    (
        0x80803E04,
        0x4,
        &[(
            255,
            9,
            "Spring-Loaded Mounting, Strange Protractor, Backup Plan",
        )],
    ),
    (
        0x80803E0C,
        0x2,
        &[
            (0, 8, "Full Auto Trigger System, Rat Pack, SUROS Rapid-Fire"),
            (1, 2, "Ahamkara's Eye, Charge Shot"),
        ],
    ),
    (
        0x80803E0C,
        0x3,
        &[
            (0, 8, "Full Auto Trigger System, Rat Pack, SUROS Rapid-Fire"),
            (1, 2, "Ahamkara's Eye, Charge Shot"),
        ],
    ),
    (
        0x80803E0D,
        0x2,
        &[(1, 7, "Häkke Precision Frame, Tracking Module, Twintails")],
    ),
    (0x80803E0F, 0x2, &[(1, 1, "Sneak Bow")]),
    (0x80803E0F, 0x3, &[(0, 1, "Sneak Bow")]),
    (0x80803E0F, 0x4, &[(0, 1, "Sneak Bow")]),
    (
        0x80803E1C,
        0x2,
        &[(0, 5, "Full Auto Trigger System, Fan Fire, Rapid-Fire Frame")],
    ),
    (
        0x80803E1C,
        0x3,
        &[
            (
                14,
                4,
                "Full Auto Trigger System, Rapid-Fire Frame, Close the Gap",
            ),
            (3, 1, "Fan Fire"),
        ],
    ),
    (
        0x80803E1D,
        0x2,
        &[
            (
                0,
                10,
                "Wish-Dragon Teeth, Probability Matrix, Helium Spirals",
            ),
            (4, 9, "Hydraulic Boosters, Mecha Holster, Linear Actuators"),
            (1, 7, "Hawkeye Hack, Uncanny Arrows, Actual Grandeur"),
            (
                2,
                7,
                "Wish-Dragon Teeth, Biotic Enhancements, Cobra Totemic",
            ),
            (3, 3, "Hydraulic Boosters, Jump Jets, Move to Survive"),
            (7, 2, "Alchemical Etchings, Double Dodge"),
        ],
    ),
    (
        0x80803E1D,
        0x3,
        &[(0, 33, "Wish-Dragon Teeth, Probability Matrix, Hawkeye Hack")],
    ),
    (
        0x80803E1D,
        0x8,
        &[
            (0, 33, "Wish-Dragon Teeth, Probability Matrix, Hawkeye Hack"),
            (1, 2, "Cross Counter, Mobius Conduit"),
        ],
    ),
    (0x80803E24, 0x2, &[(1, 1, "Upgraded Sensor Pack")]),
    (
        0x80803E2F,
        0x2,
        &[(1, 61, "Warlord's Sigil, Trench Barrel, Whirlwind Blade")],
    ),
    (
        0x80803E2F,
        0x3,
        &[(0, 61, "Warlord's Sigil, Trench Barrel, Whirlwind Blade")],
    ),
    (
        0x80803E30,
        0x4,
        &[(
            255,
            91,
            "Probability Matrix, Uncanny Arrows, Warlord's Sigil",
        )],
    ),
    (
        0x80803E39,
        0x2,
        &[(1, 5, "Burst Guard, Enduring Guard, Heavy Guard")],
    ),
    (
        0x80803E39,
        0x3,
        &[
            (0, 4, "Burst Guard, Enduring Guard, Heavy Guard"),
            (4, 1, "Tesseract"),
        ],
    ),
    (
        0x80803E3C,
        0x8,
        &[(255, 7, "Arc Conductor, Chaotic Exchanger, Riven's Curse")],
    ),
    (
        0x80803E3E,
        0x68,
        &[
            (
                0,
                16,
                "Grave Robber, Relentless Strikes, Auto Rifle Scavenger",
            ),
            (1, 11, "Grave Robber, Payday, Accomplice"),
        ],
    ),
    (
        0x80803E3E,
        0x6A,
        &[
            (0, 16, "Grave Robber, Accomplice, Auto Rifle Scavenger"),
            (1, 11, "Grave Robber, Relentless Strikes, Payday"),
        ],
    ),
    (
        0x80803E3F,
        0x68,
        &[
            (0, 14, "Tireless Blade, Arc Conductor, Superconductor"),
            (1, 10, "Triple Tap, Genesis, Thin the Herd"),
        ],
    ),
    (
        0x80803E41,
        0x2,
        &[
            (1, 4, "Hush, Solar Damage Mod, The Fundamentals"),
            (3, 4, "Telesto, Void Damage Mod, The Fundamentals"),
            (2, 3, "Anarchy, Arc Damage Mod, The Fundamentals"),
            (0, 1, "Bad Juju"),
        ],
    ),
    (
        0x80803E42,
        0x2,
        &[
            (0, 2, "Thorn Catalyst, Trinity Ghoul Catalyst"),
            (1, 2, "Striking Light, Light of the Fire"),
        ],
    ),
    (
        0x80803E42,
        0x3,
        &[(0, 4, "Thorn Catalyst, Striking Light, Light of the Fire")],
    ),
    (
        0x80803E43,
        0x4,
        &[
            (1, 12, "Sun Blast, Poison Arrows, Shield Disorient"),
            (0, 5, "Survival Well, Parting Gift, Modular Lightning"),
        ],
    ),
    (
        0x80803E44,
        0x50,
        &[
            (0, 24, "Sunfire Furnace, Dynamic Sway Reduction, Zen Moment"),
            (1, 3, "Under Pressure, High-Impact Reserves, SUROS Legacy"),
            (6, 2, "Threat Detector, Planetary Torrent"),
            (255, 2, "Ride the Bull, Honed Edge"),
            (9, 1, "Last Stand"),
        ],
    ),
    (
        0x80803E45,
        0x2,
        &[
            (
                1,
                214,
                "Spring-Loaded Mounting, Wraithmetal Mail, Upgraded Sensor Pack",
            ),
            (
                0,
                212,
                "Synapse Junctions, Probability Matrix, Wraithmetal Mail",
            ),
            (2, 29, "Spring-Loaded Mounting, Mecha Holster, Quickdraw"),
            (3, 23, "Linear Actuators, Disruption Break, Thorn Catalyst"),
        ],
    ),
    (
        0x80803E45,
        0x7,
        &[(
            0,
            414,
            "Spring-Loaded Mounting, Synapse Junctions, Probability Matrix",
        )],
    ),
    (
        0x80803E46,
        0x2,
        &[
            (1, 2, "Revolution, Kindling the Flame"),
            (3, 2, "Blessing of the Sky, Lumina Catalyst"),
        ],
    ),
    (
        0x80803E46,
        0x7,
        &[(0, 4, "Blessing of the Sky, Revolution, Lumina Catalyst")],
    ),
    (
        0x80803E47,
        0x2,
        &[(1, 9, "Delayed Gratification, Giving Hand, Special Finisher")],
    ),
    (
        0x80803E4D,
        0x2,
        &[
            (
                0,
                29,
                "Wish-Dragon Teeth, Probability Matrix, Uncanny Arrows",
            ),
            (1, 21, "Hawkeye Hack, Uncanny Arrows, Horns of Doom"),
            (2, 18, "Uncanny Arrows, Transfusion Matrix, Dreaded Visage"),
            (7, 15, "Uncanny Arrows, Dreaded Visage, Fusion Harness"),
        ],
    ),
    (
        0x80803E4D,
        0x3,
        &[
            (
                0,
                50,
                "Wish-Dragon Teeth, Probability Matrix, Uncanny Arrows",
            ),
            (1, 15, "Hawkeye Hack, Horns of Doom, Dearly Departed"),
            (2, 2, "Horns of Doom, Roving Assassin"),
        ],
    ),
    (
        0x80803E4D,
        0x4,
        &[
            (0, 61, "Wish-Dragon Teeth, Probability Matrix, Hawkeye Hack"),
            (
                1,
                4,
                "Empowering Largesse, Radiant Largesse, Embraced Largesse",
            ),
        ],
    ),
    (
        0x80803E4D,
        0x48,
        &[
            (
                255,
                42,
                "Wish-Dragon Teeth, Probability Matrix, Hawkeye Hack",
            ),
            (0, 19, "Uncanny Arrows, Actual Grandeur, Bring the Heat"),
            (11, 6, "Ashes to Assets, Enhanced Ashes to Assets, Hands-On"),
        ],
    ),
];

/// The values stock perks set for one selector byte, most used first.
#[must_use]
pub fn observed(class: u32, offset: usize) -> &'static [(u8, u32, &'static str)] {
    OBSERVED
        .iter()
        .find(|(candidate, at, _)| *candidate == class && *at == offset)
        .map_or(&[], |(_, _, values)| *values)
}
