//! The script parameters the stock banks of each slot list, from a census of the root banks.
use super::*;

/// A script parameter as the stock banks of a slot list it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct StockParameter {
    pub hash: u32,
    /// How many of the slot's banks list it.
    pub banks: usize,
    pub reset: f32,
    pub applied: f32,
    pub add: bool,
}

/// Every script parameter the stock banks of a slot list, from a census of the 54 root banks:
/// the parameter, how many of the slot's banks list it, and the reset and applied values the
/// stock rows use (the first bank's when they differ). A tuning offers these, since a listed
/// parameter is one the bank's script reads.
pub const SLOT_PARAMETERS: [(AbilityTarget, &[StockParameter]); 6] = [
    (
        GRENADE_SLOT,
        &[
            StockParameter {
                hash: 0x0E98_B133,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x1AA3_B13F,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x2F08_CD3D,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x682A_8140,
                banks: 1,
                reset: 0.0,
                applied: 3.0,
                add: false,
            },
            StockParameter {
                hash: 0x6E26_71B0,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x76FF_82D4,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7CF4_56CD,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x860B_3B0F,
                banks: 1,
                reset: 1.0,
                applied: 1.5,
                add: false,
            },
            StockParameter {
                hash: 0x8BDC_18A7,
                banks: 1,
                reset: 1.0,
                applied: 1.2,
                add: false,
            },
            StockParameter {
                hash: 0x8FB4_5D39,
                banks: 6,
                reset: 0.0,
                applied: 2.0,
                add: false,
            },
            StockParameter {
                hash: 0x9345_17D9,
                banks: 1,
                reset: 1.0,
                applied: 1.5,
                add: false,
            },
            StockParameter {
                hash: 0x99B1_D826,
                banks: 21,
                reset: 1.0,
                applied: 0.14,
                add: true,
            },
            StockParameter {
                hash: 0x99E0_42AE,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x9C78_8300,
                banks: 3,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x9ECB_F672,
                banks: 1,
                reset: 1.0,
                applied: 2.0,
                add: false,
            },
            StockParameter {
                hash: 0x9F87_2FBC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA820_9C1C,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xB0A4_D3F0,
                banks: 6,
                reset: 1.0,
                applied: 0.6,
                add: false,
            },
            StockParameter {
                hash: 0xB5C4_E5C9,
                banks: 3,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xB6C6_CA14,
                banks: 1,
                reset: 0.0,
                applied: 1.5,
                add: false,
            },
            StockParameter {
                hash: 0xB709_0D60,
                banks: 12,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xC410_3CB0,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xC5D3_BF41,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xCADD_A9DA,
                banks: 1,
                reset: 1.0,
                applied: 1.2,
                add: false,
            },
            StockParameter {
                hash: 0xE2D3_AFB7,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xEFB7_A789,
                banks: 3,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xF2CA_F468,
                banks: 1,
                reset: 0.0,
                applied: 2.0,
                add: false,
            },
            StockParameter {
                hash: 0xF599_BB5A,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xF6F1_C6C2,
                banks: 6,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
        ],
    ),
    (
        SUPER_SLOT,
        &[
            StockParameter {
                hash: 0x0A75_6E85,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x0FEA_EA74,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x22DD_02DC,
                banks: 1,
                reset: 10.0,
                applied: 7.0,
                add: false,
            },
            StockParameter {
                hash: 0x237A_CD7B,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x2768_2C62,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x2850_4837,
                banks: 1,
                reset: 4.8,
                applied: 6.8,
                add: false,
            },
            StockParameter {
                hash: 0x3288_A2AC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x45C7_9901,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x4726_5B80,
                banks: 1,
                reset: 4.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x4B51_39F9,
                banks: 1,
                reset: 1.5,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x4DA2_D8C6,
                banks: 1,
                reset: 8.0,
                applied: 4.0,
                add: false,
            },
            StockParameter {
                hash: 0x5055_A1E1,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x5A60_BD4C,
                banks: 1,
                reset: 1.0,
                applied: 0.75,
                add: false,
            },
            StockParameter {
                hash: 0x5C71_97A7,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x5DFF_DE8D,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x6626_5C09,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x686A_9475,
                banks: 2,
                reset: 1.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0x68EE_13F9,
                banks: 1,
                reset: 0.0,
                applied: 0.5,
                add: false,
            },
            StockParameter {
                hash: 0x6A44_CC21,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7417_499F,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7525_9D7C,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7C4A_C40B,
                banks: 1,
                reset: 10.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7CC8_FBDC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x8136_C08E,
                banks: 1,
                reset: 0.0,
                applied: 2.0,
                add: false,
            },
            StockParameter {
                hash: 0x8335_45DE,
                banks: 1,
                reset: 0.5,
                applied: 1.5,
                add: false,
            },
            StockParameter {
                hash: 0x8626_D0F0,
                banks: 1,
                reset: 0.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0x99C0_4C89,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x99C8_23B3,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x9D6F_1C04,
                banks: 1,
                reset: 1.0,
                applied: 1.33,
                add: false,
            },
            StockParameter {
                hash: 0x9F33_C2DC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA21F_6B1C,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA583_969F,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA593_E10D,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA957_F024,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xAA42_90AB,
                banks: 7,
                reset: 0.0,
                applied: 1.0,
                add: true,
            },
            StockParameter {
                hash: 0xB35B_A4DC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xB6B2_42C4,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xBEF8_CFC2,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xC49F_5B23,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xD18A_18C0,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xD953_C5CC,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xE77C_4A0F,
                banks: 2,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xF68F_F5F8,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
        ],
    ),
    (
        MELEE_SLOT,
        &[
            StockParameter {
                hash: 0x004F_9EC7,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x0707_CBB8,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x07CB_40DD,
                banks: 1,
                reset: 1.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0x0C69_7E26,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x19C4_F9C0,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x1C2A_B5A0,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x2497_9FFB,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x2748_AA34,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x3DDD_50F8,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x4758_3B9B,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x65D8_F47E,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x6D73_A109,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7408_0878,
                banks: 1,
                reset: 1.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0x743A_880B,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7A68_B366,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x7CC8_FBDC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x8457_AEC4,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x9118_DEA8,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x99B1_D826,
                banks: 1,
                reset: 1.0,
                applied: 0.14,
                add: true,
            },
            StockParameter {
                hash: 0x9C33_629B,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x9E20_CC5F,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA21F_6B1C,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA305_AD8E,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA4D0_E64E,
                banks: 1,
                reset: 1.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0xAF27_EE11,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xB7C0_0900,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xC9F9_4455,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xCB8D_FAA3,
                banks: 1,
                reset: 1.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0xCE32_40C0,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xD15E_686C,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xD67D_2043,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xE1FE_4C07,
                banks: 1,
                reset: 0.0,
                applied: 0.5,
                add: false,
            },
            StockParameter {
                hash: 0xE516_85C4,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xFA42_D4AA,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xFBEB_EF54,
                banks: 2,
                reset: 1.0,
                applied: 0.0,
                add: false,
            },
        ],
    ),
    (
        JUMP_SLOT,
        &[
            StockParameter {
                hash: 0x6848_7C2D,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x8136_C7A9,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
        ],
    ),
    (
        MOVEMENT_SLOT,
        &[
            StockParameter {
                hash: 0x2F0D_4DBB,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x321D_0F28,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x34B8_5318,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x3583_F41B,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x686F_5CBA,
                banks: 1,
                reset: 0.0,
                applied: 0.0,
                add: false,
            },
            StockParameter {
                hash: 0x68E4_649C,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x8B61_92E4,
                banks: 1,
                reset: 1.0,
                applied: 0.6667,
                add: false,
            },
            StockParameter {
                hash: 0x8DDD_ECCE,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xA85B_5246,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xC7B5_C10A,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xD5AC_C5E7,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xDF99_528A,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
        ],
    ),
    (
        CLASS_ABILITY_SLOT,
        &[
            StockParameter {
                hash: 0x2243_1822,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x5055_A1E1,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x6598_083A,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0x8294_8225,
                banks: 1,
                reset: 0.0,
                applied: 5.0,
                add: false,
            },
            StockParameter {
                hash: 0x9686_D294,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xB900_4A2D,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xBF88_06CC,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xE42E_75C1,
                banks: 1,
                reset: 0.042,
                applied: 0.02137,
                add: false,
            },
            StockParameter {
                hash: 0xE676_4147,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xF6C0_5CF4,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
            StockParameter {
                hash: 0xFF7B_8505,
                banks: 1,
                reset: 0.0,
                applied: 1.0,
                add: false,
            },
        ],
    ),
];

/// The parameters the stock banks of one slot list.
#[must_use]
pub fn slot_parameters(slot: AbilityTarget) -> &'static [StockParameter] {
    SLOT_PARAMETERS
        .iter()
        .find(|(candidate, _)| *candidate == slot)
        .map_or(&[], |(_, parameters)| parameters)
}
