use std::{
    collections::{BTreeSet, HashMap},
    path::{Path, PathBuf},
    sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
        mpsc,
    },
    thread,
};

use tiger_pkg::{DestinyVersion, GameVersion, PackageManager};

use crate::{
    catalog::package::{array_at, u32_at},
    hash::fnv1_name_hash,
};

const FILE_NAME: &str = "bubble_names.txt";
const FILE_SIZE_LIMIT: usize = 512 * 1024;
const SCENARIO_CLASS: u32 = 0x8080_9994;
const SCENARIO_NAME_SUFFIX: &str = ":scenario_client";
const SCENARIO_BUBBLE_DESCRIPTOR: usize = 80;
const BUBBLE_CLASS: u32 = 0x8080_924D;
const BUBBLE_STRIDE: usize = 24;
const NAMED_OBJECT_CLASS: u32 = 0x8080_9C36;
const NAME_LENGTH_LIMIT: usize = 48;
const TARGET_LIMIT: usize = 4_096;
const SWEEP_BATCH_SIZE: usize = 2_048;
const MAX_SWEEP_WORKERS: usize = 8;

enum SweepMessage {
    Progress(usize),
    Resolved(HashMap<u32, String>),
}

pub(crate) fn generate_for_install(
    install: &Path,
    settings_path: &Path,
    progress: impl FnMut(usize, usize),
) -> Result<PathBuf, String> {
    let manager = PackageManager::new(
        install.join("packages"),
        GameVersion::Destiny(DestinyVersion::Destiny2Shadowkeep),
        None,
    )
    .map_err(|error| format!("Could not open the Shadowkeep packages: {error}"))?;
    let names = scan(&manager, progress)?;
    save(settings_path, &document(&names))
}

/// Resolves the internal names whose FNV-1 hashes occur in installed destination scenarios.
/// This mirrors Sunrise's package-backed hash-name matcher: cheap named-tag paths are checked
/// first, then named-object blobs are swept for unresolved hashes.
pub(crate) fn scan(
    manager: &PackageManager,
    mut progress: impl FnMut(usize, usize),
) -> Result<Vec<String>, String> {
    let targets = collect_targets(manager)?;
    let mut resolved = HashMap::new();

    for entry in &manager.lookup.named_tags {
        for run in identifier_runs(entry.name.as_bytes()) {
            offer(run, &targets, &mut resolved);
        }
    }

    let tags = manager.get_all_by_reference(NAMED_OBJECT_CLASS);
    let tag_count = tags.len();
    progress(0, tag_count);
    if !tags.is_empty() {
        let workers = thread::available_parallelism()
            .map_or(1, usize::from)
            .min(MAX_SWEEP_WORKERS)
            .min(tag_count);
        let cursor = Arc::new(AtomicUsize::new(0));
        let (sender, receiver) = mpsc::channel();
        thread::scope(|scope| {
            for _ in 0..workers {
                let sender = sender.clone();
                let cursor = Arc::clone(&cursor);
                let tags = &tags;
                let targets = &targets;
                scope.spawn(move || {
                    let mut worker_resolved = HashMap::new();
                    loop {
                        let start = cursor.fetch_add(SWEEP_BATCH_SIZE, Ordering::Relaxed);
                        if start >= tags.len() {
                            break;
                        }
                        let end = (start + SWEEP_BATCH_SIZE).min(tags.len());
                        for (tag, _) in &tags[start..end] {
                            if let Ok(blob) = manager.read_tag(*tag) {
                                offer_blob(&blob, targets, &mut worker_resolved);
                            }
                        }
                        let _ = sender.send(SweepMessage::Progress(end - start));
                    }
                    let _ = sender.send(SweepMessage::Resolved(worker_resolved));
                });
            }
            drop(sender);
            let mut completed = 0;
            for message in receiver {
                match message {
                    SweepMessage::Progress(count) => {
                        completed += count;
                        progress(completed, tag_count);
                    }
                    SweepMessage::Resolved(worker_resolved) => {
                        merge_resolved(&mut resolved, worker_resolved);
                    }
                }
            }
        });
    }

    let mut names = resolved.into_values().collect::<Vec<_>>();
    names.sort();
    names.dedup();
    if names.is_empty() {
        return Err("The installed packages contain no resolvable Bubble names".into());
    }
    Ok(names)
}

pub(crate) fn document(names: &[String]) -> String {
    let mut names = names.to_vec();
    names.sort();
    names.dedup();
    let mut document = String::from(
        "# Generated by Sundial from the installed Destiny 2 packages.\r\n\
# One internal name per line for Sunrise's Bubble-name overlay.\r\n",
    );
    for name in names {
        document.push_str(&name);
        document.push_str("\r\n");
    }
    document
}

pub(crate) fn save(settings_path: &Path, document: &str) -> Result<PathBuf, String> {
    crate::generated_file::save(
        settings_path,
        FILE_NAME,
        document,
        FILE_SIZE_LIMIT,
        "Bubble-name file",
    )
}

fn collect_targets(manager: &PackageManager) -> Result<BTreeSet<u32>, String> {
    let mut targets = BTreeSet::new();
    let mut readable_scenarios = 0_usize;
    for entry in manager.lookup.named_tags.iter().filter(|entry| {
        entry.class_hash == SCENARIO_CLASS && entry.name.ends_with(SCENARIO_NAME_SUFFIX)
    }) {
        let Ok(scenario) = manager.read_tag(entry.hash) else {
            continue;
        };
        let Ok((count, rows, class)) = array_at(&scenario, SCENARIO_BUBBLE_DESCRIPTOR) else {
            continue;
        };
        if class != BUBBLE_CLASS {
            continue;
        }
        readable_scenarios += 1;
        for index in 0..count {
            let Ok(hash) = u32_at(&scenario, rows + index * BUBBLE_STRIDE) else {
                break;
            };
            if hash != 0 {
                targets.insert(hash);
            }
        }
    }
    if readable_scenarios == 0 {
        return Err("The installed packages contain no readable destination scenarios".into());
    }
    if targets.is_empty() {
        return Err("The installed destination scenarios contain no Bubble-name hashes".into());
    }
    if targets.len() > TARGET_LIMIT {
        return Err(format!(
            "The installed scenarios declare {} Bubble-name hashes, above Sunrise's {}-name limit",
            targets.len(),
            TARGET_LIMIT
        ));
    }
    Ok(targets)
}

fn offer_blob(blob: &[u8], targets: &BTreeSet<u32>, resolved: &mut HashMap<u32, String>) {
    for run in identifier_runs(blob) {
        offer(run, targets, resolved);
    }
}

fn identifier_runs(bytes: &[u8]) -> impl Iterator<Item = &str> {
    bytes
        .split(|byte| !is_name_character(*byte))
        .filter(|run| !run.is_empty() && run.len() <= NAME_LENGTH_LIMIT)
        // Every accepted byte is ASCII, so conversion cannot fail.
        .map(|run| unsafe { std::str::from_utf8_unchecked(run) })
}

fn offer(text: &str, targets: &BTreeSet<u32>, resolved: &mut HashMap<u32, String>) {
    if text.is_empty() || text.len() > NAME_LENGTH_LIMIT {
        return;
    }
    let mut starts = Vec::with_capacity(12);
    starts.push(0);
    for (index, byte) in text.bytes().enumerate() {
        if byte == b'_' && starts.len() < 12 {
            starts.push(index + 1);
        }
    }
    for first in 0..starts.len() {
        for last in (first + 1..=starts.len()).rev() {
            let begin = starts[first];
            let end = if last == starts.len() {
                text.len()
            } else {
                starts[last] - 1
            };
            if end <= begin {
                continue;
            }
            let candidate = &text[begin..end];
            let hash = fnv1_name_hash(candidate);
            if !targets.contains(&hash) {
                continue;
            }
            keep(hash, candidate, resolved);
        }
    }
}

fn merge_resolved(resolved: &mut HashMap<u32, String>, worker_resolved: HashMap<u32, String>) {
    for (hash, candidate) in worker_resolved {
        keep(hash, &candidate, resolved);
    }
}

fn keep(hash: u32, candidate: &str, resolved: &mut HashMap<u32, String>) {
    match resolved.get(&hash) {
        Some(current)
            if current.len() < candidate.len()
                || (current.len() == candidate.len() && current.as_str() <= candidate) => {}
        _ => {
            resolved.insert(hash, candidate.to_owned());
        }
    }
}

fn is_name_character(byte: u8) -> bool {
    byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_'
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn offers_every_underscore_bounded_subrun_and_keeps_the_shortest_name() {
        let target = fnv1_name_hash("hiveship_d2");
        let targets = BTreeSet::from([target]);
        let mut resolved = HashMap::new();
        offer("prefix_hiveship_d2_suffix", &targets, &mut resolved);
        assert_eq!(
            resolved.get(&target).map(String::as_str),
            Some("hiveship_d2")
        );

        offer("x_hiveship_d2", &targets, &mut resolved);
        assert_eq!(
            resolved.get(&target).map(String::as_str),
            Some("hiveship_d2")
        );
    }

    #[test]
    fn blob_runs_accept_only_sunrise_name_characters() {
        let runs = identifier_runs(b"AA earth_d2:path\0moon_d2").collect::<Vec<_>>();
        assert_eq!(runs, ["earth_d2", "path", "moon_d2"]);
    }
}
